import type { TemplateCatalogEntry } from './templateCatalog';

/** 会社向け・個人向けの追加テンプレート（資産化しやすい業務・生活手順） */
export const TEMPLATE_CATALOG_EXTRA: TemplateCatalogEntry[] = [
  // ── 会社向け ──
  {
    id: 'smb-it-helpdesk',
    title: 'ITヘルプデスク対応',
    category: 'smb',
    scope: 'company',
    targetAudience: ['admin', 'admin'],
    description: '社内問い合わせの受付から解決・記録までの標準フロー',
    tags: ['IT', 'ヘルプデスク', '社内'],
    imageHint: 'チケット管理画面・社内ポータルのスクショに差し替え',
    steps: [
      { type: 'normal', title: '問い合わせ内容のヒアリング', instruction: '連絡手段（チャット・メール・電話）を確認し、発生日時・利用端末・エラーメッセージを記録します。\n再現手順を口頭または画面共有で確認し、緊急度（業務停止／軽微）を分類します。' },
      { type: 'normal', title: '一次切り分けと仮対応', instruction: '再起動・キャッシュ削除・別ブラウザ確認など、安全な一次対応を実施します。\n権限変更やデータ削除が必要な場合は、承認フローに回す旨を伝えます。' },
      { type: 'check', title: 'チケット登録とエスカレーション', instruction: 'チケットシステムに事象・対応内容・担当者を登録します。\n解決見込みが当日中に難しい場合は、上長またはベンダーへエスカレーションし、依頼者へ見込み時刻を連絡します。' },
      { type: 'normal', title: '解決確認とナレッジ化', instruction: '依頼者に動作確認を依頼し、問題解消を記録します。\n再発防止のため、手順を社内ナレッジ（Clipitマニュアル等）へ追記するか既存記事を案内します。' },
    ],
  },
  {
    id: 'smb-remote-security',
    title: 'リモートワークセキュリティ',
    category: 'smb',
    scope: 'company',
    targetAudience: ['new_staff', 'admin'],
    description: '在宅勤務時の情報セキュリティ基本ルール',
    tags: ['セキュリティ', 'リモート', '社内'],
    imageHint: 'VPN・MDM設定画面のスクショに差し替え',
    steps: [
      { type: 'warning', title: '公衆Wi-Fiと画面共有の注意', instruction: 'カフェ等の公衆Wi-FiではVPN接続必須とします。画面共有時は通知・個人メール・チャットが映らないようデスクトップを整理します。' },
      { type: 'normal', title: '端末のロックと更新', instruction: '社給PCは離席時に必ずロック（Win+L / スリープ）します。\nOS・アンチウイルス・ブラウザは自動更新を有効にし、月次で再起動を実施します。' },
      { type: 'check', title: 'ファイル共有とクラウド利用', instruction: '社外へのファイル送信は承認済みクラウドのみ使用します。\n個人の無料ストレージへ業務データを保存しないことを確認します。' },
      { type: 'normal', title: 'インシデント発生時の連絡', instruction: '紛失・不正アクセス・フィッシング疑いを発見したら、直ちに情報システム担当へ連絡します。\nパスワード変更・端末隔離の指示があるまで、該当サービスへのログインを控えます。' },
    ],
  },
  {
    id: 'smb-offboarding',
    title: '退職・異動手続き',
    category: 'smb',
    scope: 'company',
    targetAudience: ['admin'],
    description: '退職者のアカウント停止・備品回収・引き継ぎ',
    tags: ['人事', '退職', '引き継ぎ'],
    imageHint: '人事システム・チェックリスト画面に差し替え',
    steps: [
      { type: 'normal', title: '退職日確定と関係部署への通知', instruction: '最終出社日・退職日を人事システムで確定し、総務・情報システム・直属上長へ通知します。' },
      { type: 'check', title: 'アカウント・権限の停止', instruction: 'メール・Slack・各種SaaS・VPNのアカウントを退職日に停止または削除します。\n共有ドライブのオーナー権限を後任へ移譲します。' },
      { type: 'normal', title: '備品・データの回収', instruction: 'PC・社員証・鍵を回収し、個人データの有無を確認します。\n業務データは所定フォルダへ移管し、ローカル保存分を消去します。' },
      { type: 'normal', title: '引き継ぎ完了の確認', instruction: '進行中案件・定期タスク・取引先連絡先を引き継ぎシートに記載します。\n上長が引き継ぎ完了を承認したら手続きをクローズします。' },
    ],
  },
  {
    id: 'smb-quality-inspection',
    title: '品質検査手順',
    category: 'smb',
    scope: 'company',
    targetAudience: ['admin'],
    description: '製品出荷前の検査・不良記録の標準手順',
    tags: ['品質', '製造', '検査'],
    imageHint: '検査シート・計測器画面に差し替え',
    steps: [
      { type: 'normal', title: '検査ロットの特定', instruction: '製造ロット番号・工程日をラベルと照合し、検査対象を特定します。' },
      { type: 'check', title: '外観・寸法の確認', instruction: 'チェックリストに沿って外観傷・寸法を計測します。基準値外れは不良票を起票し、赤ラベルで隔離します。' },
      { type: 'normal', title: '機能試験', instruction: '試験治具で通電・動作確認を実施します。異音・発熱がある場合は試験を中断し、責任者へ報告します。' },
      { type: 'check', title: '合格判定と記録', instruction: '全項目合格の場合のみ合格シールを貼付し、検査記録へ署名・日時を入力します。' },
    ],
  },
  {
    id: 'smb-sales-crm',
    title: '営業CRM入力',
    category: 'smb',
    scope: 'company',
    targetAudience: ['admin'],
    description: '商談後のCRM更新と次アクション設定',
    tags: ['営業', 'CRM', '商談'],
    imageHint: 'CRMの商談画面スクショに差し替え',
    steps: [
      { type: 'normal', title: '商談概要の記録', instruction: '訪問先・参加者・商談目的・提案内容を当日中にCRMへ入力します。' },
      { type: 'normal', title: '課題と決裁者の整理', instruction: '顧客課題・予算感・決裁フロー・競合状況をメモ欄に構造化して記載します。' },
      { type: 'check', title: '次アクションと期限', instruction: '見積提出・デモ設定など次のタスクを登録し、期限と担当を自分に設定します。' },
      { type: 'normal', title: '社内共有', instruction: '重要案件は営業チャンネルへ要点を共有し、マネージャーへ週次報告に含めます。' },
    ],
  },
  {
    id: 'smb-bcp',
    title: '災害時BCP初動',
    category: 'smb',
    scope: 'company',
    targetAudience: ['admin', 'admin'],
    description: '地震・停電発生時の初動対応チェックリスト',
    tags: ['BCP', '災害', '安全'],
    imageHint: '社内連絡網・安否確認フォームに差し替え',
    steps: [
      { type: 'warning', title: '人命安全の確保', instruction: '揺れ中は机の下へ避難。火元・倒壊物を確認し、負傷者がいれば119番通報後に応急手当を行います。' },
      { type: 'normal', title: '安否確認の開始', instruction: '安否確認システムまたはチャットで全員の無事を確認します。出社困難者は在宅継続可否をヒアリングします。' },
      { type: 'check', title: '業務影響の洗い出し', instruction: 'サーバー・電話・受注システムの稼働状況を確認し、顧客への影響がある場合は広報・営業へ連絡します。' },
      { type: 'normal', title: '復旧・代替手段の共有', instruction: 'BCPマニュアルに沿い代替拠点・リモート勤務ルールを全社へ周知します。' },
    ],
  },
  {
    id: 'clinic-sterilization',
    title: '器具滅菌・感染対策',
    category: 'clinic',
    scope: 'company',
    targetAudience: ['admin'],
    description: '診療器具の洗浄・滅菌・保管の手順',
    tags: ['滅菌', '感染対策', 'クリニック'],
    imageHint: '滅菌器・洗浄槽の写真に差し替え',
    steps: [
      { type: 'normal', title: '使用後の仮置きと洗浄', instruction: '使用直後に汚物を除去し、指定の洗浄槽へ浸漬します。乾燥前に目視で残渣がないか確認します。' },
      { type: 'check', title: 'パッキングと滅菌サイクル', instruction: '滅菌パックへ入れ、指示どおりの温度・時間でサイクルを実行します。記録票に日時・担当者を記入します。' },
      { type: 'warning', title: '滅菌失敗時の対応', instruction: 'インジケーター変色不良・機器エラー時は再滅菌または廃棄し、使用済み器具として扱いません。' },
      { type: 'normal', title: '保管と有効期限', instruction: '滅菌済み棚へ日付ラベルを貼り、先入先出で保管します。開封後は当日使用を原則とします。' },
    ],
  },
  {
    id: 'clinic-reservation',
    title: '予約変更・キャンセル',
    category: 'clinic',
    scope: 'company',
    targetAudience: ['new_staff'],
    description: '電話・Web予約の変更・キャンセル対応',
    tags: ['予約', '受付', 'クリニック'],
    imageHint: '予約システム画面に差し替え',
    steps: [
      { type: 'normal', title: '本人確認と予約内容の照合', instruction: '氏名・生年月日・予約日時を確認し、システム上の予約と一致するか照合します。' },
      { type: 'normal', title: '空き枠の案内', instruction: '変更希望日の空きを検索し、代替候補を2〜3件提示します。診療科・担当医の指定がある場合は条件を絞り込みます。' },
      { type: 'check', title: 'キャンセルポリシーの説明', instruction: '当日キャンセル料等の規定がある場合は丁寧に説明し、了承を得てから処理します。' },
      { type: 'normal', title: 'システム更新と確認連絡', instruction: '予約を変更・取消した後、SMSまたはメールで確認を送付します。待ちリストがある場合は枠を解放します。' },
    ],
  },
  {
    id: 'hospitality-opening',
    title: '店舗開店準備',
    category: 'hospitality',
    scope: 'company',
    targetAudience: ['new_staff'],
    description: '開店前の清掃・レジ準備・出品チェック',
    tags: ['開店', '店舗', 'オペレーション'],
    imageHint: '店舗内・レジ画面の写真に差し替え',
    steps: [
      { type: 'normal', title: '清掃と什器の配置', instruction: '床・テーブル・トイレを清掃し、メニュー・POP・什器を開店レイアウトどおりに配置します。' },
      { type: 'check', title: '食材・備品の確認', instruction: '期限切れ商品を廃棄し、欠品リストを作成して発注担当へ連絡します。' },
      { type: 'normal', title: 'レジ・決済端末の起動', instruction: 'レジを開局し、釣銭・レシート用紙を補充します。キャッシュレス端末の通信テストを実施します。' },
      { type: 'normal', title: '開店前ミーティング', instruction: '当日の販促・欠品・シフト変更をスタッフで共有し、開店の合図で営業開始します。' },
    ],
  },
  {
    id: 'hospitality-cashier',
    title: 'レジ締め・日次清算',
    category: 'hospitality',
    scope: 'company',
    targetAudience: ['admin'],
    description: '閉店後のレジ締めと売上報告',
    tags: ['レジ', '締め', '店舗'],
    imageHint: 'レジ締め画面・売上レポートに差し替え',
    steps: [
      { type: 'normal', title: '現金の集計', instruction: 'レジ内現金を金種ごとに数え、システム表示の理論残高と照合します。' },
      { type: 'check', title: '過不足の確認', instruction: '差異が基準額を超える場合は原因（釣銭ミス・未登録）を調査し、店長へ報告します。' },
      { type: 'normal', title: '売上データの締め', instruction: 'POSで日次締めを実行し、カード・電子マネー内訳を確認します。' },
      { type: 'normal', title: '金庫入れと報告', instruction: '売上金を金庫へ入れ、日報を本部システムへアップロードします。' },
    ],
  },
  {
    id: 'web-user-onboarding',
    title: '新規ユーザー導線',
    category: 'web',
    scope: 'company',
    targetAudience: ['admin'],
    description: 'SaaSのサインアップから初回成功体験まで',
    tags: ['オンボーディング', 'SaaS', 'UX'],
    imageHint: 'プロダクトの登録・チュートリアル画面に差し替え',
    steps: [
      { type: 'normal', title: 'アカウント作成', instruction: 'メールアドレスとパスワードを入力し、確認メールのリンクから認証を完了します。' },
      { type: 'normal', title: 'プロフィール・組織設定', instruction: '表示名・タイムゾーン・組織名を設定し、必要に応じてチームメンバーを招待します。' },
      { type: 'check', title: '初回タスクの完了', instruction: 'ウィザードに沿い、サンプルデータ作成または連携設定を完了させます。' },
      { type: 'normal', title: 'ヘルプと次のステップ', instruction: 'ヘルプセンター・サポートチャットの場所を案内し、よく使う機能へのショートカットを提示します。' },
    ],
  },
  {
    id: 'web-release-note',
    title: 'リリースノート作成',
    category: 'web',
    scope: 'company',
    targetAudience: ['admin'],
    description: '機能リリースの告知文・変更点の書き方',
    tags: ['リリース', 'changelog', 'プロダクト'],
    imageHint: 'changelogページ・管理画面に差し替え',
    steps: [
      { type: 'normal', title: '変更内容の収集', instruction: 'PR・チケットからユーザー影響のある変更を抽出し、カテゴリ（新機能・改善・修正）に分類します。' },
      { type: 'normal', title: 'ユーザー向け文案', instruction: '専門用語を避け、何ができるようになったか・何が直ったかを短文で記載します。' },
      { type: 'warning', title: '破壊的変更の明示', instruction: 'API変更・非推奨機能は目立つよう注意書きを付け、移行手順へのリンクを添えます。' },
      { type: 'check', title: '公開と社内共有', instruction: 'ヘルプサイト・メール・アプリ内お知らせへ掲載し、サポートチームへFAQを共有します。' },
    ],
  },
  {
    id: 'general-meeting',
    title: '議事録・会議進行',
    category: 'general',
    scope: 'company',
    targetAudience: ['admin'],
    description: '効果的な会議の進め方と議事録テンプレート',
    tags: ['会議', '議事録', 'ファシリテーション'],
    imageHint: '議事テンプレ・オンライン会議画面に差し替え',
    steps: [
      { type: 'normal', title: 'アジェンダの事前共有', instruction: '目的・決めること・時間配分を記載したアジェンダを24時間前までに共有します。' },
      { type: 'normal', title: '会議の開始と役割分担', instruction: '司会・書記・タイムキーパーを決め、冒頭でゴールを再確認します。' },
      { type: 'check', title: '決定事項とToDoの記録', instruction: '決定事項・担当・期限を議事録に明記します。曖昧な表現はその場で具体化します。' },
      { type: 'normal', title: '議事録の配布とフォロー', instruction: '当日中に議事録を配布し、次回までの進捗をチャットでリマインドします。' },
    ],
  },
  {
    id: 'general-vendor',
    title: '取引先登録・審査',
    category: 'general',
    scope: 'company',
    targetAudience: ['admin'],
    description: '新規ベンダー登録とコンプライアンス確認',
    tags: ['購買', 'ベンダー', 'コンプライアンス'],
    imageHint: '購買システム・申請フォームに差し替え',
    steps: [
      { type: 'normal', title: '申請情報の受領', instruction: '会社概要・インボイス登録番号・振込口座・契約書案を依頼部署から受け取ります。' },
      { type: 'check', title: '反社・与信チェック', instruction: '社内規定に沿い反社チェックと与信審査を実施し、結果を記録します。' },
      { type: 'normal', title: 'マスタ登録', instruction: '購買システムに取引先コードを発行し、支払条件・担当者を登録します。' },
      { type: 'normal', title: '関係者への通知', instruction: '登録完了を申請者・経理へ通知し、初回発注時の注意点を共有します。' },
    ],
  },
  {
    id: 'general-incident',
    title: 'インシデント報告',
    category: 'general',
    scope: 'company',
    targetAudience: ['new_staff', 'admin'],
    description: '業務上のトラブル・事故の報告フロー',
    tags: ['インシデント', '報告', '安全'],
    imageHint: 'インシデント報告フォームに差し替え',
    steps: [
      { type: 'warning', title: '即時の安全確保', instruction: '人身事故・データ漏えいの疑いがある場合は、二次被害を防ぐため現場を保全し、必要ならサービスを一時停止します。' },
      { type: 'normal', title: '一次報告', instruction: '発生日時・場所・関係者・事象を上長へ口頭またはチャットで報告します。' },
      { type: 'check', title: '公式フォームへの記録', instruction: 'インシデント管理システムへ詳細を入力し、証跡（ログ・写真）を添付します。' },
      { type: 'normal', title: '再発防止策の検討', instruction: '原因分析ミーティングを設定し、対策・マニュアル改訂の担当と期限を決めます。' },
    ],
  },
  // ── 個人向け ──
  {
    id: 'personal-pc-backup',
    title: 'PCバックアップ手順',
    category: 'general',
    scope: 'personal',
    targetAudience: ['new_staff'],
    description: '個人PCのデータを失わないための定期バックアップ',
    tags: ['バックアップ', '個人', 'デジタル'],
    imageHint: 'バックアップソフト・クラウド設定画面に差し替え',
    steps: [
      { type: 'normal', title: 'バックアップ対象の整理', instruction: '書類・写真・パスワード管理ファイルなど、失うと困るフォルダをリストアップします。' },
      { type: 'check', title: '外付けHDDまたはクラウド設定', instruction: 'Windowsのファイル履歴／macOSのTime Machine、またはクラウド同期を設定し、自動実行を有効にします。' },
      { type: 'normal', title: '復元テスト', instruction: '月に一度、テストファイルを復元してバックアップが機能しているか確認します。' },
      { type: 'warning', title: 'ランサムウェア対策', instruction: '常時接続のバックアップだけに頼らず、オフラインコピーも3-2-1ルールで保管します。' },
    ],
  },
  {
    id: 'personal-tax',
    title: '確定申告の流れ',
    category: 'general',
    scope: 'personal',
    targetAudience: ['new_staff'],
    description: '個人事業主・副業者向けの確定申告準備',
    tags: ['確定申告', '税金', '個人'],
    imageHint: 'e-Tax・会計ソフト画面に差し替え',
    steps: [
      { type: 'normal', title: '必要書類の収集', instruction: '源泉徴収票・支払調書・経費領収書・銀行通帳を年度フォルダにまとめます。' },
      { type: 'normal', title: '収支の集計', instruction: '会計ソフトまたはスプレッドシートで売上・経費を月次で入力し、科目を仕分けします。' },
      { type: 'check', title: '控除の確認', instruction: '社会保険料・小規模企業共済・ふるさと納税・医療費控除など適用可能な控除を洗い出します。' },
      { type: 'normal', title: 'e-Tax送信または提出', instruction: '作成した申告書をe-Taxで送信するか、税務署へ郵送・持参します。控えをPDF保存します。' },
    ],
  },
  {
    id: 'personal-recipe',
    title: '料理レシピ手順書',
    category: 'general',
    scope: 'personal',
    targetAudience: ['new_staff'],
    description: '家族に引き継げるレシピの書き方',
    tags: ['料理', 'レシピ', '生活'],
    imageHint: '調理工程の写真に差し替え',
    steps: [
      { type: 'normal', title: '材料と分量の記載', instruction: '人数分の材料をg・ml単位で明記し、代用可能な食材があれば併記します。' },
      { type: 'normal', title: '下準備（下ごしらえ）', instruction: '切り方・下茹で・味付けのタイミングを手順どおりに写真付きで記録します。' },
      { type: 'check', title: '加熱時間と火加減', instruction: '弱火・中火の目安と、焦げないためのコツを短いメモで残します。' },
      { type: 'normal', title: '盛り付けと保存', instruction: '完成写真と、余った場合の冷凍・冷蔵保存日数を記載します。' },
    ],
  },
  {
    id: 'personal-moving',
    title: '引っ越しチェックリスト',
    category: 'general',
    scope: 'personal',
    targetAudience: ['new_staff'],
    description: '引っ越し1ヶ月前から当日までのタスク',
    tags: ['引っ越し', '生活', 'チェックリスト'],
    imageHint: '段ボール・新居の写真に差し替え',
    steps: [
      { type: 'normal', title: '1ヶ月前：手続きと業者選定', instruction: '転出届・転入届の時期を確認し、引っ越し業者の見積もりを比較します。' },
      { type: 'check', title: '2週間前：荷造りと住所変更', instruction: '不要品を処分し、電気・ガス・インターネットの停止・開始手続きを申し込みます。' },
      { type: 'normal', title: '前日：冷蔵庫と貴重品', instruction: '冷蔵庫の中身を消化し、通帳・印鑑・PCは自分で運ぶ箱に入れます。' },
      { type: 'normal', title: '当日：立ち会いと開梱', instruction: '搬入順序を指示し、キッチン・寝具を優先して開梱します。' },
    ],
  },
  {
    id: 'personal-sidejob-invoice',
    title: '副業・請求書発行',
    category: 'general',
    scope: 'personal',
    targetAudience: ['admin'],
    description: 'フリーランス・副業の請求から入金確認まで',
    tags: ['請求書', '副業', 'フリーランス'],
    imageHint: '請求書テンプレ・会計ソフトに差し替え',
    steps: [
      { type: 'normal', title: '稼働実績の整理', instruction: '月末に稼働日・内容・単価を一覧化し、契約と突合します。' },
      { type: 'check', title: '請求書の作成', instruction: 'インボイス登録番号・振込先・支払期限を記載し、PDFで発行します。' },
      { type: 'normal', title: '送付とリマインド', instruction: 'メールで請求書を送付し、期日3日前に未払いの場合は丁寧に確認します。' },
      { type: 'normal', title: '入金・経費記録', instruction: '入金を確認したら会計ソフトへ売上計上し、源泉徴収の有無をメモします。' },
    ],
  },
  {
    id: 'personal-smartphone-setup',
    title: 'スマホ初期設定（家族向け）',
    category: 'general',
    scope: 'personal',
    targetAudience: ['new_staff'],
    description: '親世代向けスマートフォン設定の手順書',
    tags: ['スマホ', '家族', 'デジタル'],
    imageHint: '設定画面のスクリーンショットに差し替え',
    steps: [
      { type: 'normal', title: 'SIMと基本設定', instruction: 'SIMを挿入し、Wi-Fi接続・Apple ID／Googleアカウントを作成または移行します。' },
      { type: 'check', title: '文字サイズと緊急連絡', instruction: '表示サイズを大きくし、緊急連絡先を登録します。' },
      { type: 'normal', title: 'よく使うアプリのインストール', instruction: '電話・メッセージ・地図・写真の使い方を1つずつ実演します。' },
      { type: 'warning', title: 'セキュリティの注意', instruction: '知らないリンクは開かない、ストア以外からアプリを入れない旨を説明します。' },
    ],
  },
  {
    id: 'personal-travel',
    title: '旅行準備ガイド',
    category: 'general',
    scope: 'personal',
    targetAudience: ['new_staff'],
    description: '国内・海外旅行の計画から出発まで',
    tags: ['旅行', '準備', '生活'],
    imageHint: '予約確認メール・パッキング写真に差し替え',
    steps: [
      { type: 'normal', title: '日程と予約の確定', instruction: '交通・宿・主要アクティビティを予約し、確認メールをフォルダに保存します。' },
      { type: 'check', title: '持ち物リスト', instruction: '季節・目的地に合わせた持ち物をチェックし、パスポート・保険の有効期限を確認します。' },
      { type: 'normal', title: 'お金と通信', instruction: '現金・クレジットカード・海外ローミングまたはeSIMを準備します。' },
      { type: 'normal', title: '出発当日', instruction: 'チェックイン時刻・乗り場を再確認し、貴重品は手荷物に入れます。' },
    ],
  },
  {
    id: 'personal-study',
    title: '勉強・ノート術',
    category: 'education',
    scope: 'personal',
    targetAudience: ['new_staff'],
    description: '効率的なインプットと復習の手順',
    tags: ['勉強', '学習', '個人'],
    imageHint: 'ノート・学習アプリ画面に差し替え',
    steps: [
      { type: 'normal', title: 'ゴールとスケジュール', instruction: '試験日・到達目標から逆算し、週ごとの学習量を決めます。' },
      { type: 'normal', title: 'インプット（読む・聞く）', instruction: '1セッション25分で集中し、分からない用語はマージンにメモします。' },
      { type: 'check', title: 'アウトプット（要約）', instruction: '学んだ内容を自分の言葉で3行要約し、翌日に見返します。' },
      { type: 'normal', title: '週次レビュー', instruction: '理解度が低い章を再学習し、模擬問題で定着を確認します。' },
    ],
  },
  {
    id: 'personal-wedding',
    title: '結婚式準備チェックリスト',
    category: 'general',
    scope: 'personal',
    targetAudience: ['new_staff'],
    description: '挙式6ヶ月前からの準備タスク',
    tags: ['結婚式', 'イベント', '個人'],
    imageHint: '会場・招待状デザインの写真に差し替え',
    steps: [
      { type: 'normal', title: '6ヶ月前：会場と日程', instruction: '会場・日程・概算予算を決め、下見と仮予約を行います。' },
      { type: 'normal', title: '3ヶ月前：招待状と衣装', instruction: '招待状のデザイン・発送リストを確定し、衣装のフィッティングを予約します。' },
      { type: 'check', title: '1ヶ月前：席次・演出', instruction: '席次表・BGM・写真・司会進行を確定し、関係者へ役割を共有します。' },
      { type: 'normal', title: '前日・当日', instruction: '持ち物リストを確認し、二次会の連絡先・緊急連絡網を共有します。' },
    ],
  },
  {
    id: 'personal-pet-care',
    title: 'ペットの日常ケア',
    category: 'general',
    scope: 'personal',
    targetAudience: ['new_staff'],
    description: '犬猫の毎日の世話と健康管理',
    tags: ['ペット', '生活', 'ケア'],
    imageHint: 'ペット・フード・ケア用品の写真に差し替え',
    steps: [
      { type: 'normal', title: '朝の給餌と水', instruction: '決まった時間に定量のフードと新鮮な水を与えます。食べ残しは記録します。' },
      { type: 'check', title: '排泄と散歩', instruction: '排泄場所を清掃し、犬は日課の散歩で運動量を確保します。' },
      { type: 'normal', title: 'ブラッシング・歯磨き', instruction: '週数回、毛玉防止と歯石予防のケアを行います。' },
      { type: 'warning', title: '体調変化の観察', instruction: '食欲不振・嘔吐・元気なしがある場合は獣医へ連絡し、予防接種日程をカレンダー管理します。' },
    ],
  },
  {
    id: 'personal-car-maint',
    title: '車のメンテナンス',
    category: 'general',
    scope: 'personal',
    targetAudience: ['new_staff'],
    description: '日常点検と定期メンテの記録',
    tags: ['車', 'メンテナンス', '生活'],
    imageHint: '車・タイヤ・オイルゲージの写真に差し替え',
    steps: [
      { type: 'check', title: '月次の日常点検', instruction: 'タイヤ空気圧・ライト・ワイパー液を確認します。' },
      { type: 'normal', title: 'オイル・冷却水', instruction: 'エンジン停止後、レベルが目盛り内か確認します。不足時は指定品を補充します。' },
      { type: 'normal', title: '車検・点検予約', instruction: '車検満了日の3ヶ月前に予約し、整備記録をノートに残します。' },
      { type: 'warning', title: '異常時の対応', instruction: '警告灯点灯・異音時は走行を控え、ディーラーまたはロードサービスへ連絡します。' },
    ],
  },
  {
    id: 'personal-photo-organize',
    title: '写真整理・バックアップ',
    category: 'general',
    scope: 'personal',
    targetAudience: ['new_staff'],
    description: 'スマホ写真の整理と長期保存',
    tags: ['写真', '整理', 'デジタル'],
    imageHint: 'アルバムアプリ・クラウド画面に差し替え',
    steps: [
      { type: 'normal', title: 'アルバムの設計', instruction: '年・イベントごとにアルバム名を決め、重複写真の削除方針を決めます。' },
      { type: 'normal', title: 'お気に入りの選別', instruction: '月1回、ベストショットに星付けし、不要な連写を削除します。' },
      { type: 'check', title: 'クラウド同期', instruction: 'Googleフォト・iCloud等で自動バックアップを有効にします。' },
      { type: 'normal', title: '年次アーカイブ', instruction: '年末にUSBまたは外付けSSDへエクスポートし、オフライン保管します。' },
    ],
  },
  {
    id: 'personal-freelance-proposal',
    title: 'フリーランス提案書',
    category: 'general',
    scope: 'personal',
    targetAudience: ['admin'],
    description: '案件提案から契約までの文書化',
    tags: ['提案書', 'フリーランス', '営業'],
    imageHint: '提案書スライド・契約画面に差し替え',
    steps: [
      { type: 'normal', title: 'ヒアリング内容の整理', instruction: '課題・期待成果・予算・期限をメモし、提案のゴールを1文で定義します。' },
      { type: 'normal', title: '提案書の構成', instruction: '背景・提案内容・スケジュール・費用・実績を5ページ以内でまとめます。' },
      { type: 'check', title: 'レビューと送付', instruction: '誤字・金額・納期を再確認し、PDFで送付します。' },
      { type: 'normal', title: '契約とキックオフ', instruction: '合意後に契約書を締結し、キックオフ日程と連絡手段を確定します。' },
    ],
  },
  {
    id: 'personal-home-renovation',
    title: 'リフォーム進行管理',
    category: 'general',
    scope: 'personal',
    targetAudience: ['new_staff'],
    description: '自宅リフォームの業者選定から完工まで',
    tags: ['リフォーム', '住まい', '個人'],
    imageHint: '見積書・現場写真に差し替え',
    steps: [
      { type: 'normal', title: '要件と予算の定義', instruction: '必須・希望を分け、上限予算と工期の希望を文書化します。' },
      { type: 'check', title: '複数業者の見積比較', instruction: '3社以上から内訳付き見積を取得し、保証・追加費用条件を比較します。' },
      { type: 'normal', title: '契約と工程表', instruction: '契約書に工期・支払条件を明記し、工程表を共有します。' },
      { type: 'warning', title: '完工検査', instruction: '仕上がり・設備動作をチェックリストで確認し、不具合は引渡し前に是正を依頼します。' },
    ],
  },
  {
    id: 'personal-social-post',
    title: 'SNS投稿ワークフロー',
    category: 'web',
    scope: 'personal',
    targetAudience: ['admin'],
    description: '個人ブランド・副業向けの投稿手順',
    tags: ['SNS', 'マーケティング', '個人'],
    imageHint: 'SNS管理画面・投稿プレビューに差し替え',
    steps: [
      { type: 'normal', title: 'テーマとカレンダー', instruction: '週の投稿テーマを決め、下書きカレンダーに日付を入れます。' },
      { type: 'normal', title: '下書きと画像準備', instruction: '文案・ハッシュタグ・画像サイズを各プラットフォーム仕様に合わせます。' },
      { type: 'check', title: '推敲と予約投稿', instruction: '誤字・リンク・権利侵害がないか確認し、予約投稿を設定します。' },
      { type: 'normal', title: '反応の記録', instruction: '24時間後にエンゲージメントを記録し、次回の改善点をメモします。' },
    ],
  },
];
